### ISSUE TITLE
Investigar licenças para distribuição do código

### ISSUE THREAD

**Issue by ammelobr** [wolganens/edumpampa#27]
Verificar alternativas de licença, por exemplo, Software Livre, Código Aberto etc. para que possamos atribuir uma dessas licenças ao repositório e, assim, distribuí-lo para que outras pessoas, inclusive nós, possam evoluí-lo.

**Comment by wolganens** [comment]
https://en.wikipedia.org/wiki/Software_license
https://en.wikipedia.org/wiki/Free_and_open-source_software#Free_software
https://en.wikipedia.org/wiki/Free_software_license
https://choosealicense.com/licenses/
https://help.github.com/articles/licensing-a-repository/
https://github.com/blog/1530-choosing-an-open-source-license
