### ISSUE TITLE
Cadastro de OA

### ISSUE THREAD

**Issue by wolganens** [wolganens/edumpampa#32]
Ao final do cadastro de OA, redirecionar para lista de de OA's do usuário, ordenando essa lista por data de submissão (mais novos no topo) e dando destaque ao OA submetido.

**Comment by ammelobr** [comment]
No cadastro de OA, lembrar de oferecer alternativa para entrar uma licença não especificada.

**Comment by wolganens** [comment]
Aguardando commit do Murilo, pois há dependência das alterações
